/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OBS Styla API
 * API for OBS theme management and generation
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationReport } from './validationReport';

export interface ThemeValidation {
  name?: string;
  report?: ValidationReport;
  error?: string;
}
