/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OBS Styla API
 * API for OBS theme management and generation
 * OpenAPI spec version: 1.0.0
 */

export interface Theme {
  name: string;
  path: string;
  size: number;
  modified: number;
}
