/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OBS Styla API
 * API for OBS theme management and generation
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationReportSummary } from './validationReportSummary';
import type { ValidationError } from './validationError';
import type { ValidationWarning } from './validationWarning';

export interface ValidationReport {
  summary: ValidationReportSummary;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}
