/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OBS Styla API
 * API for OBS theme management and generation
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConvertRequest,
  ConvertResponse,
  GenerateResponse,
  PostThemesFilenameDuplicateBody,
  PostThemesFilenameMetaBody,
  ThemeMeta,
  ThemesResponse,
  ValidationResponse
} from '../types/orval';

import { apiMutator } from './api';
type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary Get all themes
 */
export const getThemes = (
    
 signal?: AbortSignal
) => {
      
      
      return apiMutator<ThemesResponse>(
      {url: `/themes`, method: 'GET', signal
    },
      );
    }
  



export const getGetThemesQueryKey = () => {
    return [
    `/themes`
    ] as const;
    }

    
export const getGetThemesQueryOptions = <TData = Awaited<ReturnType<typeof getThemes>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getThemes>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThemesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThemes>>> = ({ signal }) => getThemes(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThemes>>, TError, TData> & { queryKey: QueryKey }
}

export type GetThemesQueryResult = NonNullable<Awaited<ReturnType<typeof getThemes>>>
export type GetThemesQueryError = unknown


/**
 * @summary Get all themes
 */

export function useGetThemes<TData = Awaited<ReturnType<typeof getThemes>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getThemes>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetThemesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Delete a theme
 */
export const deleteThemesFilename = (
    filename: string,
 ) => {
      
      
      return apiMutator<void>(
      {url: `/themes/${filename}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteThemesFilenameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThemesFilename>>, TError,{filename: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteThemesFilename>>, TError,{filename: string}, TContext> => {

const mutationKey = ['deleteThemesFilename'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteThemesFilename>>, {filename: string}> = (props) => {
          const {filename} = props ?? {};

          return  deleteThemesFilename(filename,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteThemesFilenameMutationResult = NonNullable<Awaited<ReturnType<typeof deleteThemesFilename>>>
    
    export type DeleteThemesFilenameMutationError = unknown

    /**
 * @summary Delete a theme
 */
export const useDeleteThemesFilename = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThemesFilename>>, TError,{filename: string}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteThemesFilename>>,
        TError,
        {filename: string},
        TContext
      > => {

      const mutationOptions = getDeleteThemesFilenameMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Duplicate a theme
 */
export const postThemesFilenameDuplicate = (
    filename: string,
    postThemesFilenameDuplicateBody: PostThemesFilenameDuplicateBody,
 signal?: AbortSignal
) => {
      
      
      return apiMutator<void>(
      {url: `/themes/${filename}/duplicate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postThemesFilenameDuplicateBody, signal
    },
      );
    }
  


export const getPostThemesFilenameDuplicateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThemesFilenameDuplicate>>, TError,{filename: string;data: PostThemesFilenameDuplicateBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postThemesFilenameDuplicate>>, TError,{filename: string;data: PostThemesFilenameDuplicateBody}, TContext> => {

const mutationKey = ['postThemesFilenameDuplicate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postThemesFilenameDuplicate>>, {filename: string;data: PostThemesFilenameDuplicateBody}> = (props) => {
          const {filename,data} = props ?? {};

          return  postThemesFilenameDuplicate(filename,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostThemesFilenameDuplicateMutationResult = NonNullable<Awaited<ReturnType<typeof postThemesFilenameDuplicate>>>
    export type PostThemesFilenameDuplicateMutationBody = PostThemesFilenameDuplicateBody
    export type PostThemesFilenameDuplicateMutationError = unknown

    /**
 * @summary Duplicate a theme
 */
export const usePostThemesFilenameDuplicate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThemesFilenameDuplicate>>, TError,{filename: string;data: PostThemesFilenameDuplicateBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postThemesFilenameDuplicate>>,
        TError,
        {filename: string;data: PostThemesFilenameDuplicateBody},
        TContext
      > => {

      const mutationOptions = getPostThemesFilenameDuplicateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get theme metadata
 */
export const getThemesFilenameMeta = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return apiMutator<ThemeMeta>(
      {url: `/themes/${filename}/meta`, method: 'GET', signal
    },
      );
    }
  



export const getGetThemesFilenameMetaQueryKey = (filename?: string,) => {
    return [
    `/themes/${filename}/meta`
    ] as const;
    }

    
export const getGetThemesFilenameMetaQueryOptions = <TData = Awaited<ReturnType<typeof getThemesFilenameMeta>>, TError = unknown>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getThemesFilenameMeta>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThemesFilenameMetaQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThemesFilenameMeta>>> = ({ signal }) => getThemesFilenameMeta(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThemesFilenameMeta>>, TError, TData> & { queryKey: QueryKey }
}

export type GetThemesFilenameMetaQueryResult = NonNullable<Awaited<ReturnType<typeof getThemesFilenameMeta>>>
export type GetThemesFilenameMetaQueryError = unknown


/**
 * @summary Get theme metadata
 */

export function useGetThemesFilenameMeta<TData = Awaited<ReturnType<typeof getThemesFilenameMeta>>, TError = unknown>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getThemesFilenameMeta>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetThemesFilenameMetaQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update theme metadata
 */
export const postThemesFilenameMeta = (
    filename: string,
    postThemesFilenameMetaBody: PostThemesFilenameMetaBody,
 signal?: AbortSignal
) => {
      
      
      return apiMutator<void>(
      {url: `/themes/${filename}/meta`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postThemesFilenameMetaBody, signal
    },
      );
    }
  


export const getPostThemesFilenameMetaMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThemesFilenameMeta>>, TError,{filename: string;data: PostThemesFilenameMetaBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postThemesFilenameMeta>>, TError,{filename: string;data: PostThemesFilenameMetaBody}, TContext> => {

const mutationKey = ['postThemesFilenameMeta'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postThemesFilenameMeta>>, {filename: string;data: PostThemesFilenameMetaBody}> = (props) => {
          const {filename,data} = props ?? {};

          return  postThemesFilenameMeta(filename,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostThemesFilenameMetaMutationResult = NonNullable<Awaited<ReturnType<typeof postThemesFilenameMeta>>>
    export type PostThemesFilenameMetaMutationBody = PostThemesFilenameMetaBody
    export type PostThemesFilenameMetaMutationError = unknown

    /**
 * @summary Update theme metadata
 */
export const usePostThemesFilenameMeta = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThemesFilenameMeta>>, TError,{filename: string;data: PostThemesFilenameMetaBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postThemesFilenameMeta>>,
        TError,
        {filename: string;data: PostThemesFilenameMetaBody},
        TContext
      > => {

      const mutationOptions = getPostThemesFilenameMetaMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Generate themes
 */
export const postGenerate = (
    
 signal?: AbortSignal
) => {
      
      
      return apiMutator<GenerateResponse>(
      {url: `/generate`, method: 'POST', signal
    },
      );
    }
  


export const getPostGenerateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGenerate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postGenerate>>, TError,void, TContext> => {

const mutationKey = ['postGenerate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postGenerate>>, void> = () => {
          

          return  postGenerate()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostGenerateMutationResult = NonNullable<Awaited<ReturnType<typeof postGenerate>>>
    
    export type PostGenerateMutationError = unknown

    /**
 * @summary Generate themes
 */
export const usePostGenerate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGenerate>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postGenerate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostGenerateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Validate themes
 */
export const getValidate = (
    
 signal?: AbortSignal
) => {
      
      
      return apiMutator<ValidationResponse>(
      {url: `/validate`, method: 'GET', signal
    },
      );
    }
  



export const getGetValidateQueryKey = () => {
    return [
    `/validate`
    ] as const;
    }

    
export const getGetValidateQueryOptions = <TData = Awaited<ReturnType<typeof getValidate>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getValidate>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetValidateQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getValidate>>> = ({ signal }) => getValidate(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getValidate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetValidateQueryResult = NonNullable<Awaited<ReturnType<typeof getValidate>>>
export type GetValidateQueryError = unknown


/**
 * @summary Validate themes
 */

export function useGetValidate<TData = Awaited<ReturnType<typeof getValidate>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getValidate>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetValidateQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Convert JSON to OVT
 */
export const postConvert = (
    convertRequest: ConvertRequest,
 signal?: AbortSignal
) => {
      
      
      return apiMutator<ConvertResponse>(
      {url: `/convert`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: convertRequest, signal
    },
      );
    }
  


export const getPostConvertMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postConvert>>, TError,{data: ConvertRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postConvert>>, TError,{data: ConvertRequest}, TContext> => {

const mutationKey = ['postConvert'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postConvert>>, {data: ConvertRequest}> = (props) => {
          const {data} = props ?? {};

          return  postConvert(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostConvertMutationResult = NonNullable<Awaited<ReturnType<typeof postConvert>>>
    export type PostConvertMutationBody = ConvertRequest
    export type PostConvertMutationError = unknown

    /**
 * @summary Convert JSON to OVT
 */
export const usePostConvert = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postConvert>>, TError,{data: ConvertRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postConvert>>,
        TError,
        {data: ConvertRequest},
        TContext
      > => {

      const mutationOptions = getPostConvertMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Health check
 */
export const getHealth = (
    
 signal?: AbortSignal
) => {
      
      
      return apiMutator<void>(
      {url: `/health`, method: 'GET', signal
    },
      );
    }
  



export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
