/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OBS Styla API
 * API for OBS theme management and generation
 * OpenAPI spec version: 1.0.0
 */
import type {
  ConvertRequest,
  ConvertResponse,
  GenerateResponse,
  PostThemesFilenameDuplicateBody,
  PostThemesFilenameMetaBody,
  ThemeMeta,
  ThemesResponse,
  ValidationResponse
} from '../../types/orval';

import { apiMutator } from '.././api';



  export const getDefault = () => {
/**
 * @summary Get all themes
 */
const getThemes = (
    
 ) => {
      return apiMutator<ThemesResponse>(
      {url: `/themes`, method: 'GET'
    },
      );
    }
  /**
 * @summary Delete a theme
 */
const deleteThemesFilename = (
    filename: string,
 ) => {
      return apiMutator<void>(
      {url: `/themes/${filename}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Duplicate a theme
 */
const postThemesFilenameDuplicate = (
    filename: string,
    postThemesFilenameDuplicateBody: PostThemesFilenameDuplicateBody,
 ) => {
      return apiMutator<void>(
      {url: `/themes/${filename}/duplicate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postThemesFilenameDuplicateBody
    },
      );
    }
  /**
 * @summary Get theme metadata
 */
const getThemesFilenameMeta = (
    filename: string,
 ) => {
      return apiMutator<ThemeMeta>(
      {url: `/themes/${filename}/meta`, method: 'GET'
    },
      );
    }
  /**
 * @summary Update theme metadata
 */
const postThemesFilenameMeta = (
    filename: string,
    postThemesFilenameMetaBody: PostThemesFilenameMetaBody,
 ) => {
      return apiMutator<void>(
      {url: `/themes/${filename}/meta`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postThemesFilenameMetaBody
    },
      );
    }
  /**
 * @summary Generate themes
 */
const postGenerate = (
    
 ) => {
      return apiMutator<GenerateResponse>(
      {url: `/generate`, method: 'POST'
    },
      );
    }
  /**
 * @summary Validate themes
 */
const getValidate = (
    
 ) => {
      return apiMutator<ValidationResponse>(
      {url: `/validate`, method: 'GET'
    },
      );
    }
  /**
 * @summary Convert JSON to OVT
 */
const postConvert = (
    convertRequest: ConvertRequest,
 ) => {
      return apiMutator<ConvertResponse>(
      {url: `/convert`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: convertRequest
    },
      );
    }
  /**
 * @summary Health check
 */
const getHealth = (
    
 ) => {
      return apiMutator<void>(
      {url: `/health`, method: 'GET'
    },
      );
    }
  return {}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

